docker run -it -d \
  --label traefik.http.routers.pharmacy.rule=Host\(\`pharmacy.phamasoft.com\`\) \
  --label traefik.http.routers.pharmacy.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.pharmacy.tls=true \
  --label traefik.http.routers.pharmacy.service=pharmacy-credit-http \
  --label traefik.http.services.pharmacy-credit-http.loadbalancer.server.port=80 \
  --name dawa \
  --network web \
  --restart always \
  --expose 80 \
  emasanga/mikoposoft:may13